# Generated by Django 3.0.8 on 2020-07-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0002_auto_20200715_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='Enter Years of experience', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
    ]
