# Generated by Django 3.0.8 on 2020-07-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0003_auto_20200715_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.CharField(help_text='Enter technologies you are experienced on(if freshers mention "Fresher")', max_length=200)),
            ],
        ),
    ]
