# Generated by Django 3.0.8 on 2020-07-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0004_technology'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(help_text='Enter your skills(Technical or personal ...etc)', max_length=200)),
            ],
        ),
    ]
