# Generated by Django 3.0.8 on 2020-07-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0005_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(help_text='Enter your rating by HR', max_length=100)),
            ],
        ),
    ]
