# Generated by Django 3.0.8 on 2020-07-15 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0008_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('About', models.TextField(help_text='Resume of candidate')),
                ('education', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Resources.Edu_Qualification')),
                ('experience', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Resources.Experience')),
                ('ratings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Resources.Rating')),
                ('skills', models.ManyToManyField(help_text='enter your skills(Technical or personal ...etc)', to='Resources.Skill')),
                ('technologies', models.ManyToManyField(help_text='enter technology you are experience on(if freshers mention Fresher)', to='Resources.Technology')),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
    ]
